version: 2
#machine:
#  java:
#    version: openjdk8
#  notify:
#    branches:
#      only:
#        - master
jobs:
  build:
    machine:
      java:
        version: openjdk8
    steps:
      - checkout
      - run:
          name: Git Config
          command: 'git config --global user.email "circle@circleci.com" && git config --global user.name "CircleCI"'
      - run:
          name: Gradle Build
          command: './gradlew jar'
  test:
    machine:
      java:
        version: openjdk8
    steps:
      - run:
          name: Post Artifacts
          command: 'yes|mv -f ./build/lib/*.jar $CIRCLE_ARTIFACTS/MailW-$CIRCLE_BUILD_NUM.jar'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test